CREATE TABLE PERSONINFO(
	PERSONID INT PRIMARY KEY,
	PERSONNAME VARCHAR(100) NOT NULL,
	SALARY DECIMAL(8,2) NOT NULL,
	JOININGDATE DATETIME,
	CITY VARCHAR(100) NOT NULL,
	AGE INT,
	BIRTHDATE DATETIME NOT NULL
);

CREATE TABLE PERSONLOG(
	PLOGID INT PRIMARY KEY identity(1,1),
	PERSONID INT NOT NULL,
	PERSONNAME VARCHAR(250) NOT NULL,
	OPERATION VARCHAR(250) NOT NULL,
	UPDATEDATE DATETIME NOT NULL
);
--Part – A 
--1. Create a trigger that fires on INSERT, UPDATE and DELETE operation on the PersonInfo table to display 
--a message “Record is Affected.”
--INSERT
CREATE TRIGGER TR_INSERT_AFTER
ON PERSONINFO
AFTER INSERT 
AS BEGIN 
	PRINT 'RECORD IS AFFECTED'
END;
INSERT INTO PERSONINFO VALUES(1, 'ABC',25000,'2024-01-01','RAJKOT',23,'2001-01-01');

--UPDATE 
CREATE TRIGGER TR_UPDATE_AFTER
ON PERSONINFO
AFTER UPDATE
AS BEGIN 
	PRINT 'RECORD IS AFFECTED'
END;
UPDATE PERSONINFO
SET PERSONNAME = 'CDE'
WHERE PERSONID=1

--DELETE
CREATE TRIGGER TR_DELETE_AFTER
ON PERSONINFO
AFTER DELETE
AS BEGIN 
	PRINT 'RECORD IS AFFECTED'
END; 
DELETE FROM PERSONINFO
WHERE PERSONID=1;
--2. Create a trigger that fires on INSERT, UPDATE and DELETE operation on the PersonInfo table. For that, 
--log all operations performed on the person table into PersonLog. 
--INSERT
CREATE TRIGGER TR_PERSONAFTER_INSERT
ON PERSONINFO
AFTER INSERT
AS BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);

	SELECT @PERSONID = PERSONID FROM INSERTED
	SELECT @PERSONNAME = PERSONNAME FROM INSERTED

	INSERT INTO PERSONLOG VALUES(@PERSONID, @PERSONNAME, 'INSERTED',GETDATE())
END;
Drop Trigger TR_PERSONAFTER_INSERT
INSERT INTO PERSONINFO VALUES(23, 'mina', 1200, '2020-01-01','AMD',23,'2000-01-01');
SELECT * FROM PERSONINFO
SELECT * FROM PERSONLOG
--DELETED
CREATE OR ALTER TRIGGER TR_PERSONAFTER_DELETE
ON PERSONINFO
AFTER DELETE
AS BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);

	SELECT @PERSONID = PERSONID FROM deleted;
	SELECT @PERSONNAME = PERSONNAME FROM deleted;

	INSERT INTO PERSONLOG VALUES(@PERSONID, @PERSONNAME, 'DELETED',GETDATE())
END;
SELECT * FROM PERSONLOG
DELETE FROM PERSONINFO WHERE PERSONID=23;


--3. Create an INSTEAD OF trigger that fires on INSERT, UPDATE and DELETE operation on the PersonInfo 
--table. For that, log all operations performed on the person table into PersonLog. 
CREATE OR ALTER TRIGGER TR_INSERT_INSTEADOF 
ON PERSONINFO
INSTEAD OF INSERT
AS BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);

	SELECT @PERSONID = PERSONID FROM inserted
	SELECT @PERSONNAME = PERSONNAME FROM inserted

	INSERT INTO PERSONLOG VALUES(@PERSONID,@PERSONNAME, 'INSTEAD OF INSERT', GETDATE())
END;
INSERT INTO PERSONINFO VALUES(23, 'ABC',25000,'2024-01-01','RAJKOT',23,'2001-01-01');
SELECT * FROM PERSONINFO
SELECT * FROM PERSONLOG

--UPDATE
CREATE OR ALTER TRIGGER TR_UPDATE_INSTEADOF 
ON PERSONINFO
INSTEAD OF UPDATE
AS BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);

	SELECT @PERSONID = PERSONID FROM inserted
	SELECT @PERSONNAME = PERSONNAME FROM inserted

	INSERT INTO PERSONLOG VALUES(@PERSONID,@PERSONNAME, 'INSTEAD OF UPDATE', GETDATE())
END;
UPDATE PERSONINFO
SET PERSONNAME = 'DEF'
WHERE PERSONID=1
DROP TRIGGER TR_UPDATE_INSTEADOF
SELECT * FROM PERSONINFO
SELECT * FROM PERSONLOG

--DELETE
CREATE OR ALTER TRIGGER TR_DELETE_INSTEADOF 
ON PERSONINFO
INSTEAD OF DELETE
AS BEGIN
	DECLARE @PERSONID INT;
	DECLARE @PERSONNAME VARCHAR(100);

	SELECT @PERSONID = PERSONID FROM deleted
	SELECT @PERSONNAME = PERSONNAME FROM deleted

	INSERT INTO PERSONLOG VALUES(@PERSONID,@PERSONNAME, 'INSTEAD OF DELETE', GETDATE())
END;
DELETE FROM PERSONINFO
WHERE PERSONNAME='ABC';
SELECT * FROM PERSONINFO
SELECT * FROM PERSONLOG
--4. Create a trigger that fires on INSERT operation on the PersonInfo table to convert person name into 
--uppercase whenever the record is inserted. 
Alter TRIGGER TR_INSERT_UPPERCASE
ON PERSONINFO
AFTER INSERT
AS BEGIN 
	DECLARE @UPPER VARCHAR(100)
	DECLARE @PID INT

	SELECT @UPPER = PERSONNAME FROM inserted
	SELECT @PID = PERSONID FROM inserted

	UPDATE PERSONINFO
	SET PERSONNAME = UPPER(@UPPER)
	WHERE PERSONID = @PID
END;

Drop Trigger TR_INSERT_INSTEADOF --drop karvu padse instead of insert vadu trigger baki aa record insert nai thay
INSERT INTO PERSONINFO VALUES(11,'def',2500,'2019-01-01','RJT',23,'2005-08-23');
SELECT * FROM PERSONINFO
SELECT * FROM PERSONLOG
--5. Create trigger that prevent duplicate entries of person name on PersonInfo table. 
Create or Alter Trigger TR_PreventDuplicate
on PersonInfo
instead of insert
as begin 
	insert into PersonInfo(PERSONID,PERSONNAME, SALARY, JOININGDATE, CITY, AGE, BIRTHDATE)

	Select * from inserted
	where PERSONNAME NOT IN (select personname from PERSONINFO);
end;
insert into PERSONINFO values(22,'rashi',12000,'2021-05-01','amd',19,'2005-04-14')
insert into PERSONINFO values(23,'rashi',12000,'2021-05-01','amd',19,'2005-04-14')
select * from PERSONINFO
--6. Create trigger that prevent Age below 18 years.
CREATE TRIGGER TR_AGE_AFTER
ON PERSONINFO
AFTER INSERT
AS BEGIN
	DECLARE @AGE INT
	DECLARE @PID INT
	DECLARE @BIRTHDATE DATETIME

	SELECT @PID = PERSONID FROM inserted
	SELECT @BIRTHDATE = BIRTHDATE FROM inserted
	SET @AGE = DATEDIFF(YEAR,@BIRTHDATE,GETDATE());

	UPDATE PERSONINFO
	SET AGE = @AGE
	WHERE PERSONID = @PID;
END;
Drop trigger TR_AGE_AFTER
insert into PERSONINFO values(1,'rima',12000,'1991-01-01','rjkt',24,'1990-01-01')
select * from PERSONINFO
--Part – B 
--7. Create a trigger that fires on INSERT operation on person table, which calculates the age and update 
--that age in Person table. 
Create or Alter Trigger TR_After_updateAge
on personinfo
after insert
as begin 
	Declare @personid int
	Declare @dob Datetime;
	
	select @personid = PERSONID from inserted
	select @dob = birthdate from inserted

	update PERSONINFO
	set Age = DATEDIFF(year,@dob,GETDATE())
	where PERSONID = @personid
end;
insert into PERSONINFO values(13,'rima',12000,'1991-01-01','rjkt',24,'1990-01-01') 
select * from PERSONINFO
--8. Create a Trigger to Limit Salary Decrease by a 10%.
ALTER TRIGGER TR_SAL_DEC_UPDATE
ON PERSONINFO
AFTER UPDATE 
AS BEGIN
	DECLARE @OLDSALARY DECIMAL(8,2), @NEWSALARY DECIMAL(8,2), @PID INT

	SELECT @OLDSALARY = SALARY FROM deleted
	SELECT @NEWSALARY = SALARY FROM inserted
	SELECT @PID = PERSONID FROM inserted

	IF @NEWSALARY < @OLDSALARY *0.9
	BEGIN 
		UPDATE PERSONINFO
		SET SALARY = @OLDSALARY
		WHERE PERSONID = @PID
	END
END;

--Part – C  
--9. Create Trigger to Automatically Update JoiningDate to Current Date on INSERT if JoiningDate is NULL 
--during an INSERT. 
ALTER TRIGGER TR_AUTO_UPDATE_DATE
ON PERSONINFO 
AFTER INSERT	
AS BEGIN
	DECLARE @DATE DATETIME
	DECLARE @PERID INT

	SELECT @DATE = JOININGDATE FROM inserted
	SELECT @PERID = PERSONID FROM inserted
	IF(@DATE IS NULL)
	BEGIN 
		UPDATE PERSONINFO
		SET JOININGDATE = GETDATE()
		WHERE PERSONID = @PERID
	END
END
SELECT * FROM PERSONINFO
INSERT INTO PERSONINFO(PERSONID,PERSONNAME,SALARY,CITY,AGE,BIRTHDATE) VALUES(41,'RAM',23000,'RAJKOT',23,'1990-01-01')
--10. Create DELETE trigger on PersonLog table, when we delete any record of PersonLog table it prints 
--‘Record deleted successfully from PersonLog’.
create trigger tr_prlog_delete
on personlog
after delete
as begin
	print 'Record deleted successfully from personlog'
end
delete from PERSONLOG
where PLOGID = 1;